#!/bin/bash
psr=${1:-j1012+5307}
cp -p ../../ephemerides/psr$psr.par .
grep -n TZRFRQ psr$psr.par || \
cat <<EOD >>psr$psr.par
TZRFREQ 1400.
TZRMJD 56000.
TZRSITE coe
EOD
for site in 'gmrt' 'lofar' 'kaira'; do
  tempo2 -tempo1 -f psr$psr.par -polyco "56676 56680 300 12 12 $site 150.0"
  mv polyco_new.dat data/polyco${psr}_$site.dat
  rm polyco.tim newpolyco.dat
done
